workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: APPLE_ISSUER_ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: APPLE_KEY_ID
        APP_STORE_CONNECT_PRIVATE_KEY: APPLE_PRIVATE_KEY
        APPLE_TEAM_ID: APPLE_TEAM_ID
      node: 18.17.0
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.discoverchico.mobile
    # ... rest of configuration
